STrackerServer/STrackerServer/Models/Episode/EpisodeComment.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="EpisodeComment.cs" company="STracker">
//  Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//   Defines the EpisodeComment type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Models.Episode
{
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// The episode comment.
    /// </summary>
    public class EpisodeComment
    {
        /// <summary>
        /// Gets or sets the television show id.
        /// </summary>
        [Required]
        public string TvShowId { get; set; }

        /// <summary>
        /// Gets or sets the season number.
        /// </summary>
        [Required]
        public int SeasonNumber { get; set; }

        /// <summary>
        /// Gets or sets the episode number.
        /// </summary>
        [Required]
        public int EpisodeNumber { get; set; }

        /// <summary>
        /// Gets or sets the user id.
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// Gets or sets the Timestamp.
        /// </summary>
        public string Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the body.
        /// </summary>
        public string Body { get; set; }

        /// <summary>
        /// Gets or sets the poster.
        /// </summary>
        public string Poster { get; set; }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [Required]
        public string Id { get; set; }
    }
}

STrackerServer/STrackerServer/Models/Episode/EpisodeComments.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="EpisodeComments.cs" company="STracker">
//   Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//   The episode comments.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Models.Episode
{
    using System.Collections.Generic;

    using STrackerServer.DataAccessLayer.DomainEntities.AuxiliaryEntities;

    /// <summary>
    /// The episode comments.
    /// </summary>
    public class EpisodeComments
    {
        /// <summary>
        /// Gets or sets the television show id.
        /// </summary>
        public string TvShowId { get; set; }

        /// <summary>
        /// Gets or sets the season number.
        /// </summary>
        public int SeasonNumber { get; set; }

        /// <summary>
        /// Gets or sets the episode number.
        /// </summary>
        public int EpisodeNumber { get; set; }

        /// <summary>
        /// Gets or sets the poster.
        /// </summary>
        public string Poster { get; set; }

        /// <summary>
        /// Gets or sets the comments.
        /// </summary>
        public List<Comment> Comments { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether is moderator.
        /// </summary>
        public bool IsModerator { get; set; }
    }
}

STrackerServer/STrackerServer/Controllers/Api/AboutEpisodes_Controllers/EpisodesController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="EpisodesController.cs" company="STracker">
//  Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//  Api controller for episodes.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Controllers.Api.AboutEpisodes_Controllers
{
    using System.Net.Http;
    using System.Web.Http;

    using STrackerServer.Attributes;
    using STrackerServer.BusinessLayer.Core.EpisodesOperations;
    using STrackerServer.DataAccessLayer.DomainEntities;

    /// <summary>
    /// Episodes controller.
    /// </summary>
    public class EpisodesController : BaseController
    {
        /// <summary>
        /// The operations.
        /// </summary>
        private readonly IEpisodesOperations operations;

        /// <summary>
        /// Initializes a new instance of the <see cref="EpisodesController"/> class.
        /// </summary>
        /// <param name="episodesOperations">
        /// The episodes operations.
        /// </param>
        public EpisodesController(IEpisodesOperations episodesOperations)
        {
            this.operations = episodesOperations;
        }

        /// <summary>
        /// Get information from the episode from one season from one television show.
        /// </summary>
        /// <param name="tvshowId">
        /// The television show id.
        /// </param>
        /// <param name="seasonNumber">
        /// The season number.
        /// </param>
        /// <param name="number">
        /// The number.
        /// </param>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        [HttpGet]
        [Caching]
        public HttpResponseMessage Get(string tvshowId, int seasonNumber, int number)
        {
            return this.BaseGetForEntities<Episode, Episode.EpisodeId>(this.operations.Read(new Episode.EpisodeId { TvShowId = tvshowId, SeasonNumber = seasonNumber, EpisodeNumber = number }));
        }

        /// <summary>
        /// The get all.
        /// </summary>
        /// <param name="tvshowId">
        /// The television show id.
        /// </param>
        /// <param name="seasonNumber">
        /// The season number.
        /// </param>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        [HttpGet]
        public HttpResponseMessage GetAll(string tvshowId, int seasonNumber)
        {
            return this.BaseGet(this.operations.GetAllFromOneSeason(new Season.SeasonId { TvShowId = tvshowId, SeasonNumber = seasonNumber }));
        }
    }
}

STrackerServer/STrackerServer/Controllers/Api/EpisodesController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="EpisodesController.cs" company="STracker">
//  Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//  Controller for episodes.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Controllers.Api
{
    using System;
    using System.Net.Http;
    using System.Web.Http;

    using STrackerServer.BusinessLayer.Core.EpisodesOperations;

    /// <summary>
    /// Episodes API controller.
    /// </summary>
    public class EpisodesController : BaseController
    {
        /// <summary>
        /// The operations.
        /// </summary>
        private readonly IEpisodesOperations operations;

        /// <summary>
        /// Initializes a new instance of the <see cref="EpisodesController"/> class.
        /// </summary>
        /// <param name="episodesOperations">
        /// The episodes operations.
        /// </param>
        public EpisodesController(IEpisodesOperations episodesOperations)
        {
            this.operations = episodesOperations;
        }

        /// <summary>
        /// Get information from the episode from one season from one television show.
        /// </summary>
        /// <param name="tvshowId">
        /// The television show id.
        /// </param>
        /// <param name="seasonNumber">
        /// The season number.
        /// </param>
        /// <param name="number">
        /// The number.
        /// </param>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        [HttpGet]
        public HttpResponseMessage Get(string tvshowId, int seasonNumber, int number)
        {
            //return this.BaseGet(this.operations.Read(new Tuple<string, int, int>(tvshowId, seasonNumber, number)));
            return null;
        }

        /// <summary>
        /// The get all.
        /// </summary>
        /// <param name="tvshowId">
        /// The television show id.
        /// </param>
        /// <param name="seasonNumber">
        /// The season number.
        /// </param>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        [HttpGet]
        public HttpResponseMessage GetAll(string tvshowId, int seasonNumber)
        {
            //return this.BaseGet(this.operations.GetAllFromOneSeason(tvshowId, seasonNumber));
            return null;
        }
    }
}

STrackerServer/STrackerServer/Controllers/UsersController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="UsersController.cs" company="STracker">
//   Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//   Users web Controller.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using STrackerServer.Action_Results;
    using STrackerServer.Attributes;
    using STrackerServer.BusinessLayer.Core.UsersOperations;
    using STrackerServer.BusinessLayer.Permissions;
    using STrackerServer.DataAccessLayer.DomainEntities;
    using STrackerServer.DataAccessLayer.DomainEntities.AuxiliaryEntities;
    using STrackerServer.Models.Admin;
    using STrackerServer.Models.User;
    using STrackerServer.Models.Users;

    /// <summary>
    /// The users web controller.
    /// </summary>
    [Authorize]
    public class UsersController : Controller
    {
        /// <summary>
        /// The search max values.
        /// </summary>
        private readonly int searchMaxValues = int.Parse(ConfigurationManager.AppSettings["FE:Search:Max"]); 

        /// <summary>
        /// The users operations.
        /// </summary>
        private readonly IUsersOperations usersOperations;

        /// <summary>
        /// The permission manager.
        /// </summary>
        private readonly IPermissionManager<Permissions, int> permissionManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersController"/> class.
        /// </summary>
        /// <param name="usersOperations">
        /// The users operations.
        /// </param>
        /// <param name="permissionManager">
        /// The permission Manager.
        /// </param>
        public UsersController(IUsersOperations usersOperations, IPermissionManager<Permissions, int> permissionManager)
        {
            this.usersOperations = usersOperations;
            this.permissionManager = permissionManager;
        }

        /// <summary>
        /// The show.
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        [Authorize]
        public ActionResult Index(string id)
        {
            if (User.Identity.Name.Equals(id))
            {
                return new SeeOtherResult { Url = Url.Action("Index", "User") };
            }

            var user = this.usersOperations.Read(id);

            if (user == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("NotFound");
            }

            var currentUser = this.usersOperations.Read(User.Identity.Name);
            var isFriend = user.Friends.Any(synopsis => synopsis.Id.Equals(this.User.Identity.Name)) || user.FriendRequests.Any(synopsis => synopsis.Id.Equals(this.User.Identity.Name));
            var adminMode = this.permissionManager.HasPermission(Permissions.Admin, currentUser.Permission);

            return this.View(new UserPublicView
            {
                Id = id,
                Name = user.Name,
                PictureUrl = user.Photo,
                SubscriptionList = user.Subscriptions,
                IsFriend = isFriend,
                IsAdmin = this.permissionManager.HasPermission(Permissions.Admin, user.Permission),
                AdminMode = adminMode,
                NewEpisodes = this.usersOperations.GetUserNewEpisodes(id, DateTime.Now.AddDays(7))
            });
        }

        /// <summary>
        /// The search.
        /// </summary>
        /// <param name="name">
        /// The name.
        /// </param>
        /// <param name="page">
        /// The page.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        [Authorize]
        public ActionResult Search(string name, int? page)
        {
            if (!page.HasValue || page.Value < 0)
            {
                page = 0;
            }

            var range = new Range { Start = page.Value * this.searchMaxValues, End = ((page.Value + 1) * this.searchMaxValues) + 1 };

            var users = this.usersOperations.ReadByName(name, range);

            var hasMoreUsers = users.Count > this.searchMaxValues;

            users = users.Take(this.searchMaxValues).ToList();

            return this.View(new UserSearchResult
            {
                Result = users,
                SearchValue = name,
                CurrentPage = page.Value,
                HasMoreUsers = hasMoreUsers
            });
        }

        /// <summary>
        /// The public friends.
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        [Authorize]
        public ActionResult Friends(string id)
        {
            if (User.Identity.Name.Equals(id))
            {
                return new SeeOtherResult { Url = Url.Action("Friends", "User") };
            }

            var user = this.usersOperations.Read(id);

            if (user == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("NotFound");
            }

            return this.View(new PublicFriendsView
            {
                Id = id,
                Name = user.Name,
                List = user.Friends,
                PictureUrl = user.Photo
            });
        }

        /// <summary>
        /// The view with a form to set the specific user permission
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        [STrackerAuthorize(Permission = Permissions.Admin)]
        public ActionResult Permission(string id)
        {
            var user = this.usersOperations.Read(id);

            if (user == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("NotFound");
            }

            if (!id.Equals(User.Identity.Name) && (Permissions)user.Permission == Permissions.Admin)
            {
                Response.StatusCode = (int)HttpStatusCode.Forbidden;
                return this.View("Error", Response.StatusCode);
            }

            return this.View(new SetPermissionView
            {
                Id = user.Id,
                Name = user.Name,
                PictureUrl = user.Photo,
                PermissionName = Enum.GetName(typeof(Permissions), user.Permission),
                Permission = user.Permission,
                Permissions = this.permissionManager.GetPermissions()
            });
        }

        /// <summary>
        /// Set user permission
        /// </summary>
        /// <param name="values">
        /// The values.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        [STrackerAuthorize(Permission = Permissions.Admin)]
        public ActionResult Permission(SetPermissionView values)
        {
            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return this.View(values);
            }

            var user = this.usersOperations.Read(values.Id);

            if (!this.usersOperations.SetUserPermission(values.Id, values.Permission))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return this.View("BadRequest");
            }

            if ((User.Identity.Name.Equals(values.Id) && values.Permission < (int)Permissions.Admin) || (!User.Identity.Name.Equals(values.Id) && values.Permission == (int)Permissions.Admin))
            {
                return new SeeOtherResult { Url = Url.Action("Index", new { id = user.Id }) };
            }

            return new SeeOtherResult { Url = Url.Action("Permission", new { id = user.Id }) };
        }
    }
}

STrackerServer/STrackerServer/Views/Episodes/Comment.cshtml
@model STrackerServer.Models.Episode.EpisodeComment

@{
    ViewBag.Title = "Comment";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <img class="img-rounded" src="@Model.Poster" alt="No Artwork"/>  

            <div class="extra-padding"></div>
            <p>
                <a class="btn btn-block btn-primary" href="@Url.Action("Comments","Episodes", new { tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber, episodeNumber = Model.EpisodeNumber })">Comments</a>
            </p>
        </div> 
        <div class="span6">
            <h2>Comment</h2>
            <div class="box">
                <div class="box-whiter">
                     @Model.Body
                </div>
                @using (Html.BeginForm("Comment", "Episodes"))
                {
                    @Html.HiddenFor(comment => comment.TvShowId)
                    @Html.HiddenFor(comment => comment.SeasonNumber)
                    @Html.HiddenFor(comment => comment.EpisodeNumber)
                    @Html.HiddenFor(comment => comment.Id)
                    @Html.HiddenFor(comment => comment.Body)
                    @Html.HiddenFor(comment => comment.Poster)
                    @Html.HiddenFor(comment => comment.UserId)
                    
                    <input class="btn btn-danger" type="submit" value="Remove"/>
                }  
            </div>  
        </div>
    </div>
</div>

STrackerServer/STrackerServer/Views/Episodes/Comments.cshtml
@model STrackerServer.Models.Episode.EpisodeComments

@{
    ViewBag.Title = "Comments";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <img class="img-rounded" src="@Model.Poster" alt="No Artwork"/>  

            <div class="extra-padding"></div> 

            <p>
                <a class="btn btn-block btn-primary" href="@Url.Action("Index","Episodes", new { tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber, episodeNumber = Model.EpisodeNumber })">Season: @Model.SeasonNumber Episode: @Model.EpisodeNumber</a>
            </p> 
            <p>
                <a id="create-comment" class="btn btn-block btn-primary" href="@Url.Action("CreateComment","Episodes", new { tvshowId = Model.TvShowId })">Create Comment</a>
            </p>   
        </div> 
        <div class="span6">
            <div class="box">
                <h2 class="center">Comments</h2>
            </div>
            
            @if(Model.Comments.Count != 0)
            {
                <div class="box">
                    @foreach(var comment in Model.Comments)
                    {
                        <a href="@Url.Action("Index","Users", new { id = comment.User.Id })">@comment.User.Name</a>
                        <div class="box-whiter">
                            <div style="text-align: right">
                                @if (Model.IsModerator || User.Identity.IsAuthenticated && comment.User.Id.Equals(User.Identity.Name))
                                {
                                    <a href="@Url.Action("Comment", "Episodes", new {tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber, episodeNumber = Model.EpisodeNumber, id = comment.Id })">Edit</a>
                                }
                            </div>
                            @comment.Body
                        </div> 
                    }    
                </div>
            }
        </div>
    </div>
</div>

STrackerServer/STrackerServer/Views/Episodes/CreateComment.cshtml
@model STrackerServer.Models.Episode.EpisodeCreateComment

@{
    ViewBag.Title = "Create Comment";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <img class="img-rounded" src="@Model.Poster" alt="No Artwork"/>  

            <div class="extra-padding"></div>
            <p>
                <a class="btn btn-block btn-primary" href="@Url.Action("Comments","Episodes", new { tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber, episodeNumber = Model.EpisodeNumber })">Comments</a>
            </p> 
        </div> 
        <div class="span6">
            <div class="box">
                <h2 class="center">Create Comment</h2>
            </div>

            <div class="box">
                <div class="alert-error">
                    @Html.ValidationSummary()  
                </div>     
                @using (Html.BeginForm("CreateComment", "Episodes"))
                {
                    @Html.HiddenFor(comment => comment.TvShowId)
                    @Html.HiddenFor(comment => comment.SeasonNumber)
                    @Html.HiddenFor(comment => comment.EpisodeNumber)
                    @Html.HiddenFor(comment => comment.Poster)
                    <textarea data-val="true" data-val-required="The field is required." class="btn-block comments-textarea" id="Body" name="Body"></textarea>
                    <input class="btn btn-primary" type="submit" value="Add Comment"/>
                }   
            </div>
        </div>
    </div>
</div>

STrackerServer/STrackerServer/Views/Episodes/Index.cshtml
@model STrackerServer.Models.Episode.EpisodeView

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

@section JavaScript
{
    <script src="@Url.Content("~/Scripts/STracker/Rating.js")" type="text/javascript"></script>
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <img class="img-rounded" src="@Model.Poster" alt="No Artwork"/>  
            <div class="extra-padding"></div>
            
            @if(User.Identity.IsAuthenticated)
            {
                if (Model.IsSubscribed)
                {
                    if(Model.AsAired)
                    {
                        using (Html.BeginForm("Watched", "Episodes", new { tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber, episodeNumber = Model.EpisodeNumber }))
                        {
                            @Html.Hidden("RedirectUrl", Url.Action("Index","Episodes", new { tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber, episodeNumber = Model.EpisodeNumber }))
                            @Html.Hidden("Watched", !Model.Watched)  
                
                            if(Model.Watched)
                            {
                                <input class="btn btn-block btn-danger" type="submit" value="Uncheck"/>
                            }
                            else
                            {
                                <input class="btn btn-block btn-success" type="submit" value="Check"/>
                            }
                        }
                    }else
                    {
                        <p>
                            <button disabled="disabled" class="btn btn-block btn-success">Check(Not aired)</button>
                        </p> 
                    }  
                }
                else
                {
                    <p>
                        <a class="btn btn-block btn-success disabled" href="@Url.Action("Index","TvShows", new { id = Model.TvShowId })">Check(Need to be subscribed)</a>
                    </p> 
                } 
            }
            else
            {
                <p>
                    <a class="btn btn-block btn-success" href="@Url.Action("Login", "Account", new { returnUrl = Url.Action("Index", "Episodes", new { tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber, episodeNumber = Model.EpisodeNumber })})">Check</a>
                </p> 
            }

            <p>
                <a class="btn btn-block btn-primary" href="@Url.Action("Comments","Episodes", new { tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber, episodeNumber = Model.EpisodeNumber })">Comments</a>
            </p> 
        </div>
        <div class="span6">
            <div id="rating-result"></div>
            <div class="box">
                <h3>
                    @Model.Name
                    @for (int i = 1; i < @Model.Rating + 1; i++)
                    {
                        <img data-star-value="@i" class="star" src="@Url.Content("~/Content/images/star.png")" alt="star"/>
                    }
                    @for (int i = Model.Rating + 1; i < 6; i++)
                    {
                        <img data-star-value="@i" class="star" src="@Url.Content("~/Content/images/star_white.png")" alt="star"/>
                    }
                    <span style="font-size: 13px">from @Model.RatingsCount User(s)</span>
                    <a id="rating-link" style="font-size: 17px" href="@Url.Action("Rate","Episodes", new { tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber, episodeNumber = Model.EpisodeNumber })">
                        Rate
                    </a>
                </h3> 
                <ul class="stracker-breadcrumb">
                    <li><a href="@Url.Action("Index","TvShows", new { id = Model.TvShowId })">@Model.TvShowName</a> <span class="divider">/</span></li>
                    <li><a href="@Url.Action("Index","Seasons", new { tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber })">Season @Model.SeasonNumber</a> <span class="divider">/</span></li>
                    <li class="active">Episode @Model.EpisodeNumber</li>
                </ul>
                <p>@Model.Description</p>
                @if (User.Identity.IsAuthenticated && Model.UserRating != -1)
                {
                    <p><b>Your Rating: </b> @Model.UserRating/5</p>
                }            
                <p><b>Date: </b>@Model.Date</p>
                @if (Model.Directors.Count != 0)
                {
                    <p><b>Directors:</b></p>
                    <ul>
                        @foreach(var director in Model.Directors)
                        {
                            <li>@director.Name</li>
                        }                           
                    </ul>
                }     
                @if (Model.GuestActors.Count != 0)
                {
                    <p><b>Guest Actors:</b></p>
                    <ul>
                        @foreach (var actor in Model.GuestActors)
                        {
                            <li>@actor.Name</li>
                        }                           
                    </ul>
                }  
            </div>
            <div class="row-fluid">
                <div class="span6">
                    @if (Model.PreviousEpisode != null)
                    {
                        <a href="@Url.Action("Index","Episodes", new { tvshowId = Model.PreviousEpisode.Id.TvShowId, seasonNumber = Model.PreviousEpisode.Id.SeasonNumber, episodeNumber = Model.PreviousEpisode.Id.EpisodeNumber })">
                            Previous Episode
                        </a>
                    }
                </div>
                <div class="span6" style="text-align: right">
                    @if (Model.NextEpisode != null)
                    {
                        <a href="@Url.Action("Index","Episodes", new { tvshowId = Model.NextEpisode.Id.TvShowId, seasonNumber = Model.NextEpisode.Id.SeasonNumber, episodeNumber = Model.NextEpisode.Id.EpisodeNumber })">
                            Next Episode
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

STrackerServer/STrackerServer/Views/Episodes/Rate.cshtml
@model STrackerServer.Models.Episode.EpisodeRating

@{
    ViewBag.Title = "Rate";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <img class="img-rounded" src="@Model.Poster" alt="No Artwork"/>  

            <div class="extra-padding"></div> 

            <p>
                <a class="btn btn-block btn-primary" href="@Url.Action("Index","Episodes", new { tvshowId = Model.TvShowId, seasonNumber = Model.SeasonNumber, episodeNumber = Model.EpisodeNumber })">Season: @Model.SeasonNumber Episode: @Model.EpisodeNumber</a>
            </p> 
        </div> 
        <div class="span6">
            <div class="box">
                <h2>@Model.Name</h2> 
                <br/>
                <p><b>Rating: </b> @Model.Rating/5 (from @Model.Count Users)</p> 

                @Html.ValidationSummary()
                @using (Html.BeginForm("Rate", "Episodes"))
                {
                    @Html.HiddenFor(rating => rating.TvShowId)
                    @Html.HiddenFor(rating => rating.SeasonNumber)
                    @Html.HiddenFor(rating => rating.EpisodeNumber)

                    @Html.HiddenFor(rating => rating.Poster)
                    @Html.HiddenFor(rating => rating.Name)
                    @Html.HiddenFor(rating => rating.Rating)
                    @Html.HiddenFor(rating => rating.Count)
                    
                    
                    <div class="form-inline" style="display: inline">
                        <div style="display: inline-block">
                            <b>Your Rating: </b>
                        </div>
                        <div style="display: inline-block">
                            @Html.EditorFor(rating => rating.Value)
                        </div>
                        <div style="display: inline-block">
                            <input class="btn btn-danger" type="submit" value="Rate"/>
                        </div>
                    </div>
                }  
            </div>
        </div>
    </div>
</div>