STrackerServer/STrackerServer/Models/User/FriendView.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="FriendView.cs" company="STracker">
//  Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//  The friend view.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Models.User
{
    /// <summary>
    /// The friend view.
    /// </summary>
    public class FriendView
    {
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the picture url.
        /// </summary>
        public string PictureUrl { get; set; }
    }
}

STrackerServer/STrackerServer/Models/User/FriendsView.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="FriendsView.cs" company="STracker">
//   Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//   The friends view.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Models.User
{
    using System.Collections.Generic;

    /// <summary>
    /// The friends view.
    /// </summary>
    public class FriendsView
    {
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the picture url.
        /// </summary>
        public string PictureUrl { get; set; }

        /// <summary>
        /// Gets or sets the subscription list.
        /// </summary>
        public List<DataAccessLayer.DomainEntities.User.UserSynopsis> List { get; set; }
    }
}

STrackerServer/STrackerServer/Controllers/Api/EpisodesWatchedController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="EpisodesWatchedController.cs" company="STracker">
//  Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//   The episodes watched controller.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Controllers.Api
{
    using System.Net.Http;
    using System.Web.Http;

    using STrackerServer.Attributes;
    using STrackerServer.BusinessLayer.Core.UsersOperations;

    /// <summary>
    /// The episodes watched controller.
    /// </summary>
    public class EpisodesWatchedController : BaseController
    {
        /// <summary>
        /// The users operations.
        /// </summary>
        private readonly IUsersOperations usersOperations;

        /// <summary>
        /// Initializes a new instance of the <see cref="EpisodesWatchedController"/> class.
        /// </summary>
        /// <param name="usersOperations">
        /// The users operations.
        /// </param>
        public EpisodesWatchedController(IUsersOperations usersOperations)
        {
            this.usersOperations = usersOperations;
        }

        /// <summary>
        /// The post.
        /// </summary>
        /// <param name="tvshowId">
        /// The television show id.
        /// </param>
        /// <param name="seasonNumber">
        /// The season number.
        /// </param>
        /// <param name="episodeNumber">
        /// The episode number.
        /// </param>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        [HttpPost]
        [HawkAuthorize]
        public HttpResponseMessage Post(string tvshowId, int seasonNumber, int episodeNumber)
        {
            //return this.BasePostDelete(this.usersOperations.AddWatchedEpisode(User.Identity.Name, tvshowId, seasonNumber, episodeNumber));
            return null;
        }

        /// <summary>
        /// The delete.
        /// </summary>
        /// <param name="tvshowId">
        /// The television show id.
        /// </param>
        /// <param name="seasonNumber">
        /// The season number.
        /// </param>
        /// <param name="episodeNumber">
        /// The episode number.
        /// </param>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        [HttpDelete]
        [HawkAuthorize]
        public HttpResponseMessage Delete(string tvshowId, int seasonNumber, int episodeNumber)
        {
            //return this.BasePostDelete(this.usersOperations.RemoveWatchedEpisode(User.Identity.Name, tvshowId, seasonNumber, episodeNumber));
            return null;
        }
    }
}

STrackerServer/STrackerServer/Controllers/EpisodesWebController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="EpisodesWebController.cs" company="STracker">
//   Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//   Defines the EpisodesWebController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Controllers
{
    using System;
    using System.Globalization;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using STrackerServer.Action_Results;
    using STrackerServer.Attributes;
    using STrackerServer.BusinessLayer.Core.EpisodesOperations;
    using STrackerServer.BusinessLayer.Core.TvShowsOperations;
    using STrackerServer.BusinessLayer.Core.UsersOperations;
    using STrackerServer.BusinessLayer.Permissions;
    using STrackerServer.DataAccessLayer.DomainEntities;
    using STrackerServer.DataAccessLayer.DomainEntities.AuxiliaryEntities;
    using STrackerServer.Models.Episode;

    /// <summary>
    /// The episodes web controller.
    /// </summary>
    public class EpisodesWebController : ControllerExtensions
    {
        /// <summary>
        /// The episodes operations.
        /// </summary>
        private readonly IEpisodesOperations episodesOps;

        /// <summary>
        /// The television shows ops.
        /// </summary>
        private readonly ITvShowsOperations tvshowsOps;

        /// <summary>
        /// The comments operations.
        /// </summary>
        private readonly IEpisodesCommentsOperations commentsOperations;

        /// <summary>
        /// The ratings operations.
        /// </summary>
        private readonly IEpisodesRatingsOperations ratingsOperations;

        /// <summary>
        /// The users operations.
        /// </summary>
        private readonly IUsersOperations usersOperations;

        /// <summary>
        /// The permission manager.
        /// </summary>
        private readonly IPermissionManager<Permissions, int> permissionManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="EpisodesWebController"/> class.
        /// </summary>
        /// <param name="episodesOps">
        /// The episodes ops.
        /// </param>
        /// <param name="tvshowsOps">
        /// The television shows ops.
        /// </param>
        /// <param name="commentsOperations">
        /// The comments operations.
        /// </param>
        /// <param name="ratingsOperations">
        /// The ratings operations.
        /// </param>
        /// <param name="usersOperations">
        /// The users operations.
        /// </param>
        /// <param name="permissionManager">
        /// The permission manager.
        /// </param>
        public EpisodesWebController(IEpisodesOperations episodesOps, ITvShowsOperations tvshowsOps, IEpisodesCommentsOperations commentsOperations, IEpisodesRatingsOperations ratingsOperations, IUsersOperations usersOperations, IPermissionManager<Permissions, int> permissionManager)
        {
            this.episodesOps = episodesOps;
            this.tvshowsOps = tvshowsOps;
            this.commentsOperations = commentsOperations;
            this.ratingsOperations = ratingsOperations;
            this.usersOperations = usersOperations;
            this.permissionManager = permissionManager;
        }

        /// <summary>
        /// The episode main view.
        /// </summary>
        /// <param name="tvshowId">
        /// The television show id.
        /// </param>
        /// <param name="seasonNumber">
        /// The season number.
        /// </param>
        /// <param name="episodeNumber">
        /// The episode Number.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        public ActionResult Index(string tvshowId, int seasonNumber, int episodeNumber)
        {
            var key = new Episode.EpisodeId { TvShowId = tvshowId, SeasonNumber = seasonNumber, EpisodeNumber = episodeNumber };

            var episode = this.episodesOps.Read(key);

            if (episode == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("Error", Response.StatusCode);
            }

            var tvshow = this.tvshowsOps.Read(tvshowId);
            var episodeRating = this.ratingsOperations.Read(key);

            var isSubscribed = false;
            var watched = false;
            Rating userRating = null;

            if (User.Identity.IsAuthenticated)
            {
                var user = this.usersOperations.Read(User.Identity.Name);
                var subscription = user.Subscriptions.Find(subscription1 => subscription1.TvShow.Id.Equals(tvshowId));

                if (subscription != null)
                {
                    isSubscribed = true;
                    watched = subscription.EpisodesWatched.Exists(synopsis => synopsis.Equals(episode.GetSynopsis()));
                }

                userRating = episodeRating.Ratings.Find(rating => rating.User.Id.Equals(user.Id));
            }

            var asAired = false;

            if (!episode.Date.Equals(NotAvailable))
            {
                DateTime date;

                if (DateTime.TryParseExact(episode.Date, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out date))
                {
                    asAired = !(DateTime.Compare(date, DateTime.Now) > 0);
                }
            }

            return this.View(new EpisodeView
            {
                TvShowId = episode.Id.TvShowId,
                SeasonNumber = episode.Id.SeasonNumber,
                EpisodeNumber = episode.Id.EpisodeNumber,
                Description = episode.Description,
                Name = episode.Name,
                GuestActors = episode.GuestActors,
                Directors = episode.Directors,
                Poster = episode.Poster,
                TvShowName = tvshow.Name,
                Date = episode.Date,
                Rating = (int)episodeRating.Average,
                IsSubscribed = isSubscribed,
                Watched = watched,
                AsAired = asAired,
                RatingsCount = episodeRating.Ratings.Count,
                UserRating = userRating != null ? userRating.UserRating : -1
            });
        }

        /// <summary>
        /// The comments of the episode.
        /// </summary>
        /// <param name="tvshowId">
        /// The television show id.
        /// </param>
        /// <param name="seasonNumber">
        /// The season number.
        /// </param>
        /// <param name="episodeNumber">
        /// The episode number.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        public ActionResult Comments(string tvshowId, int seasonNumber, int episodeNumber)
        {
            var key = new Episode.EpisodeId { TvShowId = tvshowId, SeasonNumber = seasonNumber, EpisodeNumber = episodeNumber };
            var episodeComments = this.commentsOperations.Read(key);
            
            if (episodeComments == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("Error", Response.StatusCode);
            }

            var episode = this.episodesOps.Read(key);

            var isModerator = false;

            if (User.Identity.IsAuthenticated)
            {
                var user = this.usersOperations.Read(User.Identity.Name);
                isModerator = this.permissionManager.HasPermission(Permissions.Moderator, user.Permission);
            }

            var view = new EpisodeComments
                {
                    TvShowId = tvshowId,
                    SeasonNumber = seasonNumber,
                    EpisodeNumber = episodeNumber,
                    Comments = episodeComments.Comments,
                    Poster = episode.Poster,
                    IsModerator = isModerator
                };

            return this.View(view);
        }

        /// <summary>
        /// The create comment.
        /// </summary>
        /// <param name="tvshowId">
        /// The television show id.
        /// </param>
        /// <param name="seasonNumber">
        /// The season number.
        /// </param>
        /// <param name="episodeNumber">
        /// The episode number.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        [Authorize]
        public ActionResult CreateComment(string tvshowId, int seasonNumber, int episodeNumber)
        {
            var key = new Episode.EpisodeId { TvShowId = tvshowId, SeasonNumber = seasonNumber, EpisodeNumber = episodeNumber };
            var episode = this.episodesOps.Read(key);

            if (episode == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("Error", Response.StatusCode);
            }

            var view = new EpisodeCreateComment
                {
                    TvShowId = tvshowId,
                    SeasonNumber = seasonNumber,
                    EpisodeNumber = episodeNumber,
                    Poster = episode.Poster,
                };

            return this.View(view);
        }

        /// <summary>
        /// The create comment.
        /// </summary>
        /// <param name="create">
        /// The create.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        [Authorize]
        public ActionResult CreateComment(EpisodeCreateComment create)
        {

STrackerServer/STrackerServer/Controllers/SeasonsWebController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SeasonsWebController.cs" company="STracker">
//  Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//  Season Web Controller
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Controllers
{
    using System;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using Models.Season;

    using STrackerServer.BusinessLayer.Core.SeasonsOperations;
    using STrackerServer.BusinessLayer.Core.TvShowsOperations;

    /// <summary>
    /// The season web controller.
    /// </summary>
    public class SeasonsWebController : Controller
    {
        /// <summary>
        /// The season operations.
        /// </summary>
        private readonly ISeasonsOperations seasonOps;

        /// <summary>
        /// The television shows ops.
        /// </summary>
        private readonly ITvShowsOperations tvshowsOps;

        /// <summary>
        /// Initializes a new instance of the <see cref="SeasonsWebController"/> class.
        /// </summary>
        /// <param name="seasonOps">
        /// The season ops.
        /// </param>
        /// <param name="tvshowsOps">
        /// The television shows ops.
        /// </param>
        public SeasonsWebController(ISeasonsOperations seasonOps, ITvShowsOperations tvshowsOps)
        {
            this.seasonOps = seasonOps;
            this.tvshowsOps = tvshowsOps;
        }

        /// <summary>
        /// The show.
        /// </summary>
        /// <param name="tvshowId">
        /// The television show id.
        /// </param>
        /// <param name="seasonNumber">
        /// The season Number.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        public ActionResult Show(string tvshowId, int seasonNumber)
        {
            var season = this.seasonOps.Read(new Tuple<string, int>(tvshowId, seasonNumber));

            if (season == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("Error", Response.StatusCode);
            }

            var tvshow = this.tvshowsOps.Read(tvshowId);

            return this.View(new SeasonView
            {
                TvShowId = tvshowId,
                EpisodeList = season.EpisodeSynopsis.OrderBy(ep => ep.EpisodeNumber),
                SeasonNumber = season.SeasonNumber,
                Poster = tvshow.Poster,
                TvShowName = tvshow.Name   
            });
        }
    }
}

STrackerServer/STrackerServer/Views/UsersWeb/EpisodesWatched.cshtml
@model STrackerServer.Models.User.EpisodesWatchedView

@{
    ViewBag.Title = "Episodes Watched";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="box">
                <div style="text-align: center">
                    <a href="@Url.Action("Index","UsersWeb")">
                        <img class="img-rounded" src="@Model.PictureUrl" alt="No Artwork"/>
                    </a>
                </div> 
                <div class="extra-padding"></div>
                <p><a class="btn btn-block btn-primary" href="@Url.Action("Friends","UsersWeb")">Friends</a></p>
                <p><a class="btn btn-block btn-primary" href="@Url.Action("Suggestions","UsersWeb")">Sugestions</a></p>
                <p><a class="btn btn-block btn-primary" href="@Url.Action("Requests","UsersWeb")">Friend Requests</a></p> 
                <p><a class="btn btn-block btn-primary" href="@Url.Action("EpisodesWatched","UsersWeb")">Episodes Watched</a></p>  
            </div>
        </div>

        <div class="span6">
            <div class="box center">
                <h2>Episodes Watched</h2> 
            </div>
            
            @foreach(var sub in Model.List.Where(view => view.EpisodesWatched.Count != 0))
            {
                <div class="box">
                    <h3>
                        <a href="@Url.Action("Show", "TvShowsWeb", new { tvshowId = sub.TvShow.Id })">
                           @sub.TvShow.Name 
                        </a>
                    </h3> 
                    <br/>
                    
                    @foreach(var season in sub.EpisodesWatched.Keys.OrderBy(i => i))
                    {           
                        <div class="box-whiter">
                            <h4>
                                <a href="@Url.Action("Show", "SeasonsWeb", new { tvshowId = sub.TvShow.Id , seasonNumber = season })">
                                    Season @season
                                </a>
                            </h4> 
                            <br/>
                            <table class="table table-condensed">
                                @foreach(var episode in sub.EpisodesWatched[season].OrderBy(synopsis => synopsis.EpisodeNumber))
                                {
                                    <tr>
                                        
                                        <td>
                                            @episode.EpisodeNumber
                                            <span> - </span>
                                            <a href="@Url.Action("Show","EpisodesWeb", new { tvshowId = episode.TvShowId, seasonNumber = episode.SeasonNumber, episodeNumber = episode.EpisodeNumber })">
                                                @episode.Name
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </table>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>

STrackerServer/STrackerServer/Views/UsersWeb/Friends.cshtml
@model STrackerServer.Models.User.FriendsView

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="box">
                <div style="text-align: center">
                    <a href="@Url.Action("Index","UsersWeb")">
                        <img class="img-rounded" src="@Model.PictureUrl" alt="No Artwork"/>
                    </a>
                </div> 
                <div class="extra-padding"></div>
                <p><a class="btn btn-block btn-primary" href="@Url.Action("Friends","UsersWeb")">Friends</a></p>
                <p><a class="btn btn-block btn-primary" href="@Url.Action("Suggestions","UsersWeb")">Sugestions</a></p>
                <p><a class="btn btn-block btn-primary" href="@Url.Action("Requests","UsersWeb")">Friend Requests</a></p> 
                <p><a class="btn btn-block btn-primary" href="@Url.Action("EpisodesWatched","UsersWeb")">Episodes Watched</a></p> 
            </div>
        </div>

        <div class="span6">
            <div class="box center">
                <h2>Friends</h2> 
            </div>
            @if (Model.List.Count != 0)
            {
                <div class="box">    
                    <table class="table table-condensed">
                        @foreach (var friend in Model.List)
                        {
                            <tr>
                                <td>
                                    <a href="@Url.Action("Show","UsersWeb", new { id = friend.Id })">@friend.Name</a>
                                </td>
                                <td>
                                    @using (Html.BeginForm("RemoveFriend", "UsersWeb", new { friendId = friend.Id }))
                                    {
                                        <input class="btn btn-mini btn-block btn-danger" type="submit" value="Remove"/>
                                    }
                                </td>
                            </tr>
                         }
                    </table>
                </div>
             }
        </div>
    </div>
</div>

STrackerServer/STrackerServer/Views/UsersWeb/GetByName.cshtml
@model STrackerServer.Models.User.UserSearchResult

@{
    ViewBag.Title = "Search User";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="row center">
                @using (Html.BeginForm("GetByName", "UsersWeb", FormMethod.Get))
                {
                    <div class="form-inline">
                        <span>Name:</span> 
                        <input id="UserSearch" type="text" name="name" value="@Model.SearchValue" class="input-large"/>
                        <button type="submit" class="btn btn-primary"><b class="icon-search"></b></button>
                    </div>                 
                }
            </div>
        </div>
    </div>
    @{
        for (var i = 0; i < Math.Ceiling(Model.Result.Count / (double)6); i++)
        {
            <div class="row-fluid">
                @for (var index = 6*i; (index < (6 * (i+1))) && index < Model.Result.Count; index++)
                {
                    <div class="span2" style="text-align: center">
                        <div class="box-whiter">
                            <div class="row-fluid">
                                <img src="@Model.Result[index].Photo" alt="No Image"/>
                            </div>
                            <br/>
                            <div class="row-fluid">
                                 <a class="btn btn-block btn-primary" href="@Url.Action("Show","UsersWeb", new { id = Model.Result[index].Id })">@Model.Result[index].Name</a>
                            </div>
                        </div>
                    </div>
                }     
            </div>
        }
    }
</div>

STrackerServer/STrackerServer/Views/UsersWeb/PublicFriends.cshtml
@model STrackerServer.Models.User.PublicFriendsView

@{
    ViewBag.Title = "Friends";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="box">
                <div style="text-align: center">
                    <a href="@Url.Action("Show","UsersWeb", new { id = Model.Id })">
                       <img class="img-rounded" src="@Model.PictureUrl" alt="No Artwork"/> 
                    </a>
                </div> 
                <div class="extra-padding"></div>
                <p><a class="btn btn-block btn-primary" href="@Url.Action("Show","UsersWeb", new { id = Model.Id })">@Model.Name</a></p> 
                <a class="btn btn-block btn-primary" href="@Url.Action("PublicFriends","UsersWeb", new { id = Model.Id })">Friends</a>
            </div>
        </div>

        <div class="span6">
            <div class="box">
                <h2 class="center">Friends</h2> 
            </div>
            @if (Model.List.Count != 0)
            {
                <div class="box">
                    <table class="table table-condensed">
                        @foreach (var friend in Model.List)
                        {
                            <tr>
                                <td>
                                    <a href="@Url.Action("Show","UsersWeb", new { id = friend.Id })">@friend.Name</a>
                                </td>
                            </tr>
                        }   
                    </table>
                </div> 
            } 
        </div>
    </div>
</div>

STrackerServer/STrackerServer/Views/UsersWeb/Requests.cshtml
@model STrackerServer.Models.User.Requests

@{
    ViewBag.Title = "Friend Requests";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="box">
                <div style="text-align: center">
                    <a href="@Url.Action("Index","UsersWeb")">
                        <img class="img-rounded" src="@Model.PictureUrl" alt="No Artwork"/>
                    </a>
                </div> 
                <div class="extra-padding"></div>
                <p><a class="btn btn-block btn-primary" href="@Url.Action("Friends","UsersWeb")">Friends</a></p>
                <p><a class="btn btn-block btn-primary" href="@Url.Action("Suggestions","UsersWeb")">Sugestions</a></p>
                <p><a class="btn btn-block btn-primary" href="@Url.Action("Requests","UsersWeb")">Friend Requests</a></p> 
                <p><a class="btn btn-block btn-primary" href="@Url.Action("EpisodesWatched","UsersWeb")">Episodes Watched</a></p>  
            </div>
        </div>

        <div class="span6">
            <div class="box center">
                <h2>Friend Requests</h2> 
            </div>
 
            @if (Model.List.Count != 0)
            {
                <div class="box">
                    <table class="table table-condensed">
                        @foreach(var request in Model.List)
                        {
                            <tr>
                                <td>
                                    <a href="@Url.Action("Show","UsersWeb", new { id = request.Id })">@request.Name</a>
                                </td>
                                <td>
                                    @using(Html.BeginForm("RequestResponse","UsersWeb", new {id = request.Id}))
                                    {
                                        @Html.Hidden("accept", true)
                                        <input class="btn btn-mini btn-block btn-success" type="submit" value="Accept" />
                                    }
                                </td>
                                <td>
                                    @using (Html.BeginForm("RequestResponse", "UsersWeb", new { id = request.Id }))
                                    {
                                        @Html.Hidden("accept", false)
                                        <input class="btn btn-mini btn-block btn-danger" type="submit"  value="Reject"/>
                                    }
                                </td>
                            </tr>
                         }
                    </table>     
                </div>
            }       
        </div>
    </div>
</div>