STrackerServer/STrackerServer/Controllers/Api/AboutTvShows_Controllers/TvShowsController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TvShowsController.cs" company="STracker">
//  Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//  Api Controller for television shows.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Controllers.Api.AboutTvShows_Controllers
{
    using System.Net.Http;
    using System.Web.Http;

    using STrackerServer.Attributes;
    using STrackerServer.BusinessLayer.Core.TvShowsOperations;
    using STrackerServer.DataAccessLayer.DomainEntities;
    using STrackerServer.DataAccessLayer.DomainEntities.AuxiliaryEntities;

    /// <summary>
    /// Television shows API controller.
    /// </summary>
    public class TvShowsController : BaseController
    {
        /// <summary>
        /// Operations object.
        /// </summary>
        private readonly ITvShowsOperations operations;

        /// <summary>
        /// Initializes a new instance of the <see cref="TvShowsController"/> class.
        /// </summary>
        /// <param name="tvshowsOperations">
        /// Television shows operations.
        /// </param>
        public TvShowsController(ITvShowsOperations tvshowsOperations)
        {
            this.operations = tvshowsOperations;
        }

        /// <summary>
        /// Get one television show by id.
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        [HttpGet]
        [Caching]
        public HttpResponseMessage Get(string id)
        {
            return this.BaseGetForEntities<TvShow, string>(this.operations.Read(id));
        }

        /// <summary>
        /// Get one or more television shows by name.
        /// </summary>
        /// <param name="name">
        /// The name for search.
        /// </param>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        [HttpGet]
        public HttpResponseMessage GetByName(string name)
        {
            return this.BaseGet(this.operations.ReadByName(name, new Range()));
        }

        /// <summary>
        /// Get one or more television shows by name. Receives also a range 
        /// for get only one portion of television shows.
        /// </summary>
        /// <param name="name">
        /// The name.
        /// </param>
        /// <param name="start">
        /// The start value of the range.
        /// </param>
        /// <param name="end">
        /// The end value of the range.
        /// </param>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        [HttpGet]
        public HttpResponseMessage GetByNameWithRange(string name, int start, int end)
        {
            return this.BaseGet(this.operations.ReadByName(name, new Range { Start = start, End = end }));
        }
    }
}

STrackerServer/STrackerServer/Controllers/Api/TvShowsController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TvShowsController.cs" company="STracker">
//  Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//  Controller for television shows.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Controllers.Api
{
    using System;
    using System.Configuration;
    using System.Net.Http;
    using System.Web.Http;

    using STrackerServer.BusinessLayer.Core.TvShowsOperations;

    /// <summary>
    /// Television shows API controller.
    /// </summary>
    public class TvShowsController : BaseController
    {
        /// <summary>
        /// The max top rated television shows.
        /// </summary>
        private static readonly int MaxTopRatedTvShows = Convert.ToInt32(ConfigurationManager.AppSettings["MaxTopRatedTvShows"]);

        /// <summary>
        /// The operations.
        /// </summary>
        private readonly ITvShowsOperations operations;

        /// <summary>
        /// Initializes a new instance of the <see cref="TvShowsController"/> class.
        /// </summary>
        /// <param name="tvshowsOperations">
        /// Television shows operations.
        /// </param>
        public TvShowsController(ITvShowsOperations tvshowsOperations)
        {
            this.operations = tvshowsOperations;
        }

        /// <summary>
        /// Get information from the television show with id.
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        [HttpGet]
        public HttpResponseMessage Get(string id)
        {
            return this.BaseGet(this.operations.Read(id));
        }

        /// <summary>
        /// Get one television show by name.
        /// </summary>
        /// <param name="name">
        /// The name.
        /// </param>
        /// <returns>
        /// The <see>
        ///       <cref>IEnumerable</cref>
        ///     </see> .
        /// </returns>
        public HttpResponseMessage GetByName(string name)
        {
            return this.BaseGet(this.operations.ReadByName(name));
        }

        /// <summary>
        /// The get top rated.
        /// </summary>
        /// <returns>
        /// The <see cref="HttpResponseMessage"/>.
        /// </returns>
        public HttpResponseMessage GetTopRated()
        {
            //return this.BaseGet(this.operations.GetTopRated(MaxTopRatedTvShows));
            return null;
        }
    }
}

STrackerServer/STrackerServer/Controllers/GenresController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="GenresController.cs" company="STracker">
//  Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//   The genre web controller.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Controllers
{
    using System.Net;
    using System.Web.Mvc;

    using STrackerServer.BusinessLayer.Core;
    using STrackerServer.Models.Genre;

    /// <summary>
    /// The genre web controller.
    /// </summary>
    public class GenresController : Controller
    {
        /// <summary>
        /// The max television shows returned.
        /// </summary>
        public const int MaxTvShows = 6; 

        /// <summary>
        /// The genre operations.
        /// </summary>
        private readonly IGenresOperations genreOperations;

        /// <summary>
        /// Initializes a new instance of the <see cref="GenresController"/> class. 
        /// </summary>
        /// <param name="genreOperations">
        /// The genre operations.
        /// </param>
        public GenresController(IGenresOperations genreOperations)
        {
            this.genreOperations = genreOperations;
        }

        /// <summary>
        /// Represents all the television shows in the specific genre.
        /// </summary>
        /// <param name="id">
        /// The genre name.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        public ActionResult Index(string id)
        {
            var genre = this.genreOperations.Read(id);

            if (genre == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("NotFound");
            }

            return this.View(new GenreView { GenreName = genre.Id, TvShows = genre.Tvshows });
        }

        /// <summary>
        /// The get television shows with the most percentage of genres.
        /// </summary>
        /// <param name="genres">
        /// The genres.
        /// </param>
        /// <param name="excludeTvShow">
        /// The exclude television show.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        public ActionResult GetSimilar(string[] genres, string excludeTvShow)
        {
            var tvshows = this.genreOperations.GetTvShows(genres, excludeTvShow, MaxTvShows);

            if (tvshows.Count == 0)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return null;
            }

            return this.View(new SimilarTvShowsView { TvShows = tvshows });
        }
    }
}

STrackerServer/STrackerServer/Controllers/UsersController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="UsersController.cs" company="STracker">
//   Copyright (c) STracker Developers. All rights reserved.
// </copyright>
// <summary>
//   Users web Controller.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace STrackerServer.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    using STrackerServer.Action_Results;
    using STrackerServer.Attributes;
    using STrackerServer.BusinessLayer.Core.UsersOperations;
    using STrackerServer.BusinessLayer.Permissions;
    using STrackerServer.DataAccessLayer.DomainEntities;
    using STrackerServer.DataAccessLayer.DomainEntities.AuxiliaryEntities;
    using STrackerServer.Models.Admin;
    using STrackerServer.Models.User;
    using STrackerServer.Models.Users;

    /// <summary>
    /// The users web controller.
    /// </summary>
    [Authorize]
    public class UsersController : Controller
    {
        /// <summary>
        /// The search max values.
        /// </summary>
        private readonly int searchMaxValues = int.Parse(ConfigurationManager.AppSettings["FE:Search:Max"]); 

        /// <summary>
        /// The users operations.
        /// </summary>
        private readonly IUsersOperations usersOperations;

        /// <summary>
        /// The permission manager.
        /// </summary>
        private readonly IPermissionManager<Permissions, int> permissionManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersController"/> class.
        /// </summary>
        /// <param name="usersOperations">
        /// The users operations.
        /// </param>
        /// <param name="permissionManager">
        /// The permission Manager.
        /// </param>
        public UsersController(IUsersOperations usersOperations, IPermissionManager<Permissions, int> permissionManager)
        {
            this.usersOperations = usersOperations;
            this.permissionManager = permissionManager;
        }

        /// <summary>
        /// The show.
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        [Authorize]
        public ActionResult Index(string id)
        {
            if (User.Identity.Name.Equals(id))
            {
                return new SeeOtherResult { Url = Url.Action("Index", "User") };
            }

            var user = this.usersOperations.Read(id);

            if (user == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("NotFound");
            }

            var currentUser = this.usersOperations.Read(User.Identity.Name);
            var isFriend = user.Friends.Any(synopsis => synopsis.Id.Equals(this.User.Identity.Name)) || user.FriendRequests.Any(synopsis => synopsis.Id.Equals(this.User.Identity.Name));
            var adminMode = this.permissionManager.HasPermission(Permissions.Admin, currentUser.Permission);

            return this.View(new UserPublicView
            {
                Id = id,
                Name = user.Name,
                PictureUrl = user.Photo,
                SubscriptionList = user.Subscriptions,
                IsFriend = isFriend,
                IsAdmin = this.permissionManager.HasPermission(Permissions.Admin, user.Permission),
                AdminMode = adminMode,
                NewEpisodes = this.usersOperations.GetUserNewEpisodes(id, DateTime.Now.AddDays(7))
            });
        }

        /// <summary>
        /// The search.
        /// </summary>
        /// <param name="name">
        /// The name.
        /// </param>
        /// <param name="page">
        /// The page.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        [Authorize]
        public ActionResult Search(string name, int? page)
        {
            if (!page.HasValue || page.Value < 0)
            {
                page = 0;
            }

            var range = new Range { Start = page.Value * this.searchMaxValues, End = ((page.Value + 1) * this.searchMaxValues) + 1 };

            var users = this.usersOperations.ReadByName(name, range);

            var hasMoreUsers = users.Count > this.searchMaxValues;

            users = users.Take(this.searchMaxValues).ToList();

            return this.View(new UserSearchResult
            {
                Result = users,
                SearchValue = name,
                CurrentPage = page.Value,
                HasMoreUsers = hasMoreUsers
            });
        }

        /// <summary>
        /// The public friends.
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        [Authorize]
        public ActionResult Friends(string id)
        {
            if (User.Identity.Name.Equals(id))
            {
                return new SeeOtherResult { Url = Url.Action("Friends", "User") };
            }

            var user = this.usersOperations.Read(id);

            if (user == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("NotFound");
            }

            return this.View(new PublicFriendsView
            {
                Id = id,
                Name = user.Name,
                List = user.Friends,
                PictureUrl = user.Photo
            });
        }

        /// <summary>
        /// The view with a form to set the specific user permission
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpGet]
        [STrackerAuthorize(Permission = Permissions.Admin)]
        public ActionResult Permission(string id)
        {
            var user = this.usersOperations.Read(id);

            if (user == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.View("NotFound");
            }

            if (!id.Equals(User.Identity.Name) && (Permissions)user.Permission == Permissions.Admin)
            {
                Response.StatusCode = (int)HttpStatusCode.Forbidden;
                return this.View("Error", Response.StatusCode);
            }

            return this.View(new SetPermissionView
            {
                Id = user.Id,
                Name = user.Name,
                PictureUrl = user.Photo,
                PermissionName = Enum.GetName(typeof(Permissions), user.Permission),
                Permission = user.Permission,
                Permissions = this.permissionManager.GetPermissions()
            });
        }

        /// <summary>
        /// Set user permission
        /// </summary>
        /// <param name="values">
        /// The values.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        [HttpPost]
        [STrackerAuthorize(Permission = Permissions.Admin)]
        public ActionResult Permission(SetPermissionView values)
        {
            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return this.View(values);
            }

            var user = this.usersOperations.Read(values.Id);

            if (!this.usersOperations.SetUserPermission(values.Id, values.Permission))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return this.View("BadRequest");
            }

            if ((User.Identity.Name.Equals(values.Id) && values.Permission < (int)Permissions.Admin) || (!User.Identity.Name.Equals(values.Id) && values.Permission == (int)Permissions.Admin))
            {
                return new SeeOtherResult { Url = Url.Action("Index", new { id = user.Id }) };
            }

            return new SeeOtherResult { Url = Url.Action("Permission", new { id = user.Id }) };
        }
    }
}

STrackerServer/STrackerServer/Views/TvShows/Comment.cshtml
@model STrackerServer.Models.TvShow.TvShowComment

@{
    ViewBag.Title = "Comment";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <img class="img-rounded" src="@Model.Poster" alt="No Artwork"/>  

            <div class="extra-padding"></div>
            <p>
                <a class="btn btn-block btn-primary" href="@Url.Action("Comments","TvShows", new { id = Model.TvShowId })">Comments</a>
            </p>
        </div> 
        <div class="span6">
            <h2>Comment</h2>
            <div class="box">
                <div class="box-whiter">
                     @Model.Body
                </div>
                @using (Html.BeginForm("Comment", "TvShows"))
                {
                    @Html.HiddenFor(comment => comment.Body)
                    @Html.HiddenFor(comment => comment.Id)
                    @Html.HiddenFor(comment => comment.Poster)
                    @Html.HiddenFor(comment => comment.TvShowId)
                    @Html.HiddenFor(comment => comment.UserId)

                    <input class="btn btn-danger" type="submit" value="Remove"/>
                }  
            </div>  
        </div>
    </div>
</div>

STrackerServer/STrackerServer/Views/TvShows/Comments.cshtml
@model STrackerServer.Models.TvShow.TvShowComments

@{
    ViewBag.Title = "Comments";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <img class="img-rounded" src="@Model.Poster" alt="No Artwork"/>  

            <div class="extra-padding"></div> 

            <p>
                <a class="btn btn-block btn-primary" href="@Url.Action("Index","TvShows", new { id = Model.TvShowId })">@Model.TvShowName</a>
            </p> 

            <p>
                <a id="create-comment" data-toggle="modal" class="btn btn-block btn-primary" href="@Url.Action("CreateComment","TvShows", new { tvshowId = Model.TvShowId })">Create Comment</a>
            </p> 
            
            <div id="myModal" class="modal hide fade" style="color: black">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3>Modal header</h3>
                </div>
              <div class="modal-body">
                <p>One fine body…</p>
              </div>
              <div class="modal-footer">
                <a href="#" class="btn">Close</a>
                <a href="#" class="btn btn-primary">Save changes</a>
              </div>
            </div>

            
        </div> 
        <div class="span6">
            <div class="box">
                <h2 class="center">Comments</h2>
            </div>
            
            @if(Model.Comments.Count != 0)
            {
                <div class="box">    
                    @foreach(var comment in Model.Comments)
                    {
                        <a href="@Url.Action("Index","Users", new { id = comment.User.Id })">@comment.User.Name</a>
                        <div class="box-whiter">
                            <div style="text-align: right">
                                @if (User.Identity.IsAuthenticated && (Model.IsModerator || comment.User.Id.Equals(User.Identity.Name)))
                                {
                                    <a href="@Url.Action("Comment", "TvShows", new {tvshowId = Model.TvShowId, id = comment.Id })">Edit</a>
                                }
                            </div>
                            @comment.Body
                        </div> 
                    }   
                </div>
            }
        </div>
    </div>
</div>

STrackerServer/STrackerServer/Views/TvShows/Index.cshtml
@model STrackerServer.Models.TvShow.TvShowView

@{
    ViewBag.Title = @Model.Name;
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

@section JavaScript
{
    <script src="@Url.Content("~/Scripts/STracker/SimilarTvShows.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/STracker/Rating.js")" type="text/javascript"></script>
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <img class="img-rounded" src="@Model.Poster" alt="No Artwork"/>  

            <div class="extra-padding"></div> 
            @if (User.Identity.IsAuthenticated)
            {
                using (Html.BeginForm("Subscribe", "TvShows", new { id = Model.TvShowId }))
                {
                    @Html.Hidden("RedirectUrl", Url.Action("Index","TvShows", new { id = Model.TvShowId }))

                    if (Model.IsSubscribed)
                    {
                        @Html.Hidden("isSubscribing", false)
                        <input class="btn btn-block btn-danger" type="submit" value="Unsubscribe"/>
                    }else
                    {
                        @Html.Hidden("isSubscribing", true)
                        <input class="btn btn-block btn-success" type="submit" value="Subscribe"/>
                    }  
                }  
            }else
            { 
                <a class="btn btn-block btn-success" href="@Url.Action("Login","Account", new { returnUrl =  Url.Action("Index","TvShows", new { id = Model.TvShowId })})">Subscribe</a>
                <div class="extra-padding"></div> 
            }
            
            <p>
                <a class="btn btn-block btn-primary" href="@Url.Action("Suggest","TvShows", new { id = Model.TvShowId })">Suggest</a>
            </p>  
            <p>
                <a class="btn btn-block btn-primary" href="@Url.Action("Comments","TvShows", new { id = Model.TvShowId })">Comments</a>
            </p>
        </div> 
        <div class="span6">
            <div id="rating-result"></div>
            <div class="box">
                <h2>
                    @Model.Name
                    @for (int i = 1; i < @Model.Rating+1; i++)
                    {
                        <img data-star-value="@i" class="star" src="@Url.Content("~/Content/images/star.png")" alt="star"/>
                    }
                    @for (int i = Model.Rating+1; i < 6; i++)
                    {
                        <img data-star-value="@i" class="star" src="@Url.Content("~/Content/images/star_white.png")" alt="star"/>           
                    }
                    <span style="font-size: 13px">from @Model.RatingsCount User(s)</span>
                    <a id="rating-link" style="font-size: 17px" href="@Url.Action("Rate","TvShows", new { id = Model.TvShowId })">
                        Rate
                    </a>
                </h2>
                <br/>
                <p>@Model.Description</p> 
                @if (User.Identity.IsAuthenticated && Model.UserRating != -1)
                {
                    <p><b>Your Rating: </b> @Model.UserRating/5</p>
                }
                
                <p><b>First Aired: </b> @Model.FirstAired</p>
                <p><b>Air Day: </b> @Model.AirDay</p>
                <p><b>Runtime: </b> @Model.Runtime min</p>              
                <p><a href="http://www.imdb.com/title/@Model.TvShowId">IMDB</a> ID: @Model.TvShowId</p>  

                <p><b>Genre:</b></p>
                <ul>
                    @foreach(var genre in Model.Genres)
                    {
                        <li>
                            <a class="genre" href="@Url.Action("Index","Genres", new { id = genre.Id })">@genre.Id</a>
                        </li>            
                    }
                </ul>
            </div>     
            <div class="box">
                <b> Seasons:</b>
                
                @foreach (var season in Model.SeasonSynopses)
                {
                    <a href="@Url.Action("Index", "Seasons", new { tvshowId = season.Id.TvShowId, seasonNumber = season.Id.SeasonNumber })">@season.Id.SeasonNumber</a><b> | </b>
                }
            </div>
            <div id="display-season" class="box hide">
                <div style="text-align: right">
                    <button class="btn-link" id="display-hide">Close</button>
                </div>         
                <br/>
                <table id="display-table" class="table table-condensed">

                </table>
            </div> 
            <div class="box">
                <h3>Cast</h3>
                <br/>              
                <table id="cast-table" class="table table-condensed">
                    <tr>
                        <th>Photo</th>
                        <th>Name</th>
                        <th>Character</th>
                    </tr>
        
                    @foreach(var actor in Model.Actors)
                    {
                        <tr>
                            <td>
                                <img class="icon-actor" src="@actor.Photo" alt="No Artwork"/>
                            </td>
                            <td>
                                @actor.Name
                            </td>
                            <td>
                                @actor.CharacterName
                            </td>
                        </tr>  
                    }
                </table>
            </div>     
        </div>
        <div class="span3">
            @if(Model.NewEpisodes.Count != 0)
            {
                <div class="box grey-border">
                    <h2 class="grey-text" style="text-align: center">Next episodes</h2>                        
                    @foreach(var episode in Model.NewEpisodes)
                    {
                        <dl>              
                            <dt>@episode.Date</dt>
                            <dd>
                                <span>S</span>@if(episode.Id.SeasonNumber < 10){<span>0</span>}@episode.Id.SeasonNumber
                                <span>E</span>@if(episode.Id.EpisodeNumber < 10){<span>0</span>}@episode.Id.EpisodeNumber
                                <span> - </span>
                                <a href="@Url.Action("Index","Episodes", new { tvshowId = episode.Id.TvShowId, seasonNumber = episode.Id.SeasonNumber, episodeNumber = episode.Id.EpisodeNumber })">@episode.Name</a>
                            </dd>           
                        </dl>       
                    }
                </div>
            }
            <div id="similar-tvshows">
                <span id="tvshowId" class="hidden">@Model.TvShowId</span>
            </div>
        </div>
    </div>
</div>

STrackerServer/STrackerServer/Views/TvShows/Suggest.cshtml
@model STrackerServer.Models.User.SuggestView

@{
    ViewBag.Title = "Suggest";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

@section JavaScript
{
    <script src="@Url.Content("~/Scripts/STracker/SuggestionHandler.js")" type="text/javascript"></script>
}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <img class="img-rounded" src="@Model.Poster" alt="No Artwork"/>
            <div class="extra-padding"></div> 
            <p>
                <a class="btn btn-block btn-primary" href="@Url.Action("Index","TvShows", new { id = Model.TvShowId })">@Model.TvShowName</a>
            </p> 
        </div> 

        <div class="span6">
            <div class="box">
                <h3>Friends</h3>
                <br/>
                <table class="table table-condensed">
                    <tr>                       
                        <th>Name</th>
                        <th></th>
                    </tr>
                    
                    @foreach(var friend in Model.Friends)
                    {
                        <tr>
                            <td>
                                <a href="@Url.Action("Index","Users", new { id = friend.Id })">@friend.Name</a>
                            </td>
                            <td style="text-align: right">
                                @if(friend.IsSubscribed)
                                {
                                    <div style="text-align: right">Already Subscribed</div>
                                }else
                                {
                                    using(Html.BeginForm("Suggest","TvShows", FormMethod.Post, new { type="suggest", data_username=friend.Name, data_id= friend.Id }))
                                    {
                                        @Html.Hidden("FriendId",friend.Id)
                                        @Html.HiddenFor(view => view.TvShowId)
                                        <input class="btn btn-primary" type="submit" value="Suggest"/>
                                    }
                                }
                            </td>
                        </tr>  
                    }
                </table>
            </div>
        </div> 
        <div class="span3">
            <div id="suggestion-result" data-tvshow="@Model.TvShowId"></div>
        </div>     
    </div>
</div>